SELECT *FROM EMP;
SELECT ENAME ,JOB
FROM EMP
WHERE JOB ='MANAGER';
SELECT ENAME
    (CASE 
     WHEN DEPTNO =  
	               ( SELECT DEPTNO  
                    FROM DEPT
				    WHERE JOB NOT LIKE 'S%'))
FROM EMP;
SELECT ENAME,EMPNO,JOB
FROM EMP E
WHERE 1000 <= (SELECT SAL
                FROM 
				WHERE EMPNO = E.EMPNO);