SELECT DEPTNO,JOB,SUM(SAL) TOTAL
FROM EMP
GROUP BY DEPTNO,JOB;
SELECT JOB,AVG(SAL) AS AVEREAGE
FROM EMP GROUP BY JOB;
SELECT DEPTNO,MIN(SAL)
FROM EMP
GROUP BY DEPTNO;
SELECT DEPTNO,AVG(SAL) AS AVGESAL
FROM EMP
GROUP BY DEPTNO;
SELECT MAX(COMM) AS HIGNCOMM
FROM EMP;
SELECT COUNT(DISTINCT DEPTNO) AS COUNT
FROM EMP;
SELECT DEPTNO,COUNT(JOB)
FROM EMP
GROUP BY DEPTNO;
SELECT DEPTNO,SUM(SAL) FROM EMP GROUP BY DEPTNO;
SELECT AVG(SAL) FROM EMP WHERE JOB = 'MANAGER';
SELECT AVG(SAL) FROM EMP WHERE JOB = 'SALESMAN';
